# Generated by Django 2.2.5 on 2020-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Supervisor')], null=True),
        ),
    ]
