# Generated by Django 2.2.5 on 2020-07-19 10:05

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Not Set', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='admission_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=userprofile.models.user_directory_path),
        ),
    ]
