# Generated by Django 2.2.5 on 2020-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
